macro(UnsetIfUpdated UnsetVar WatchedVar)
    if(DEFINED CACHE{OLD_${WatchedVar}})
        if(NOT ${WatchedVar} STREQUAL OLD_${WatchedVar})
            unset(${UnsetVar} CACHE)
        endif()
    endif()
    set(OLD_${WatchedVar} ${${WatchedVar}} CACHE INTERNAL "previous value of ${WatchedVar}")
endmacro()

macro(IfUpdatedUnsetAll)
    set(UnsetVars "${ARGN}")
    list(REMOVE_AT UnsetVars 0)
    set(WatchedVar "${ARGV0}")
    if(DEFINED CACHE{OLD_${WatchedVar}})
        if(NOT ${WatchedVar} STREQUAL OLD_${WatchedVar})
            foreach(UnsetVar IN LISTS UnsetVars)
                unset(${UnsetVar} CACHE)
            endforeach()
        endif()
    endif()
    set(OLD_${WatchedVar} ${${WatchedVar}} CACHE INTERNAL "previous value of ${WatchedVar}")
endmacro()
