macro(UnsetIfUpdated UnsetVar WatchedVar)
    if(NOT ${WatchedVar} STREQUAL OLD_${WatchedVar})
        set(OLD_${WatchedVar} ${${WatchedVar}} CACHE INTERNAL "previous value of ${WatchedVar}")
        unset(${UnsetVar} CACHE)
    endif()
endmacro()

macro(IfUpdatedUnsetAll)
    set(UnsetVars "${ARGN}")
    list(REMOVE_AT UnsetVars 0)
    set(WatchedVar "${ARGV0}")
    if(NOT ${WatchedVar} STREQUAL OLD_${WatchedVar})
        set(OLD_${WatchedVar} ${${WatchedVar}} CACHE INTERNAL "previous value of ${WatchedVar}")
        foreach(UnsetVar IN LISTS UnsetVars)
            unset(${UnsetVar} CACHE)
        endforeach()
    endif()
endmacro()
